name: greenhouse
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-VariableFont_wght.ttf
        - asset: fonts/Nunito-Italic-VariableFont_wght.ttf
  assets:
    - assets/logo/logo.svg
    - assets/logo/logo_white.svg
    - assets/icons/clock.svg
    - assets/icons/archive.svg
    - assets/icons/statistics.svg
    - assets/mushroom_images/mushroom.jpeg
    - assets/icons/plant.svg
    - assets/mushroom_images/champis.png
